imports:
    - { resource: repositories.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Form\Type\ValueVoucherType: ~
    AppBundle\Form\Type\TreatmentVoucherType: ~
