parameters:
    #

services:
    _defaults:
        autowire: true

    AppBundle\Repository\ShopRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Shop

    AppBundle\Repository\UserRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\User

    AppBundle\Repository\VoucherRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Voucher

    AppBundle\Service\CsvWriter: ~

    AppBundle\Service\VoucherFinder:
        arguments:
            - "@=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:Voucher')"
            - "%vouchers_per_page%"

    AppBundle\Service\UserFinder:
        arguments:
            - "@=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:User')"
            - "%vouchers_per_page%"
