imports:
    - { resource: repositories.yml }
    - { resource: form_types.yml }

services:
    _defaults:
        autowire: true

    AppBundle\Service\CsvWriter: ~

    AppBundle\Service\VoucherFinder:
        arguments:
            - "@=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:Voucher')"
            - "%vouchers_per_page%"

    AppBundle\Service\UserFinder:
        arguments:
            - "@=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:User')"
            - "%vouchers_per_page%"
