parameters:
    #

services:
    shop.repository:
        class: AppBundle\Repository\ShopRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Shop

    user.repository:
        class: AppBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\User

    voucher.repository:
        class: AppBundle\Repository\VoucherRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Voucher

    csv.writer:
        class: AppBundle\Service\CsvWriter
        autowire: true

    voucher.finder:
        class: AppBundle\Service\VoucherFinder
        autowire: true

    user.finder:
        class: AppBundle\Service\UserFinder
        autowire: true

    voucher.code.generator:
        class: AppBundle\Service\VoucherCodeGenerator
        autowire: true