---
- name: MySQL | install mysql packages
  apt: pkg={{ item }} state=installed
  with_items:    
   - mysql-client
   - mysql-common
   - mysql-server
   - python-mysqldb
  become: yes
  become_user: root

- name: MySQL | Delete anonymous MySQL server user for localhost
  mysql_user: name="" state="absent" host=localhost login_user=root login_password=root
  become: yes
  become_user: root

- name: MySQL | Create root@% user with all privileges
  mysql_user: name=root password=root priv=*.*:ALL state="present" host='%' login_user=root login_password=root
  become: yes
  become_user: root

- name: MySQL | Delete root@localhost user
  mysql_user: name=root state="absent" host=localhost login_user=root login_password=root
  become: yes
  become_user: root

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password=root

- name: Create database
  mysql_db:
    name: floathamburg
    state: present
    login_user: root
    login_password: root

- name: MySQL | restart mysql
  notify: restart mysql
  service: name=mysql enabled=yes state=started
