---
- name: Install php7.1-cli
  become: yes
  apt:
    pkg: php7.1-cli
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"

- name: Install php7.1-fpm
  become: yes
  apt:
    pkg: php7.1-fpm
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_fpm_state }}"
  notify: restart php7.1-fpm

- name: Install PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_packages }}"

- name: Install dev PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_dev_packages }}"
  when: not ansidev_production

- name: Install production PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_production_packages }}"
  when: ansidev_production

- name: Install xDebug
  become: yes
  apt:
    pkg: php-xdebug
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  when: "{{ php_xdebug }}"

- include: configure.yml
