---
- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest
  tags: nginx

- name: Remove default site config
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Remove default site config
  become: yes
  file: path=/etc/nginx/sites-available/default state=absent
  notify: reload nginx

- name: Change default nginx site
  become: yes
  template: src=etc/nginx/conf.d/vagrant.conf.tpl dest=/etc/nginx/conf.d/vagrant.conf
  notify: restart nginx
  when: dev_env
  tags: nginx

- name: Change default nginx site
  become: yes
  template: src=etc/nginx/conf.d/production.conf.tpl dest=/etc/nginx/conf.d/production.conf
  notify: restart nginx
  when: not dev_env
  tags: nginx

- name: Enable nginx service
  service: name=nginx enabled=yes state=started
