---
- hosts: local
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - server
    - git
    - nginx
    - php
    - nodejs
    - curl
    - wget
    - composer
    - mysql

- hosts: remote
  become: yes
  become_method: sudo
  roles:
    - server
    - git
    - nginx
    - php
    - nodejs
    - curl
    - wget
    - composer
    - mysql
    - symfony
